# Generated by Django 5.0.6 on 2024-06-20 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitioWeb', '0005_rename_id_asist_asistencia_id_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Resultado_eta',
        ),
    ]
